language: php

php:
  - 5.5
  - 5.6
  - '7'

before_script:
  - cp .env.travis .env
  - mysql -e 'create database test_timegrid;'
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan migrate
  - php artisan db:seed
  - php artisan geoip:update

script:
  - vendor/bin/phpunit